using System;
using System.Collections;
using System.IO;

namespace OwlDotNetApi
{
	/// <summary>
	/// Represents an OWL Generator
	/// </summary>
	public interface IOwlGenerator
	{
		/// <summary>
		/// Indicates whether the generator should throw an exception and stop when it encounters an error
		/// </summary>
		bool StopOnErrors
		{
			get;
			set;
		}
		
		/// <summary>
		/// Indicates whether the generator should throw an exception and stop when it encounters a warning
		/// </summary>
		bool StopOnWarnings
		{
			get;
			set;
		}

		/// <summary>
		/// Represents a list of warning messages generated by the generator
		/// </summary>
		ArrayList Warnings
		{
			get;
		}

		/// <summary>
		/// Represents a list of error messages generated by the generator
		/// </summary>
		ArrayList Errors
		{
			get;
		}

		/// <summary>
		/// Represents a list of logging messages
		/// </summary>
		ArrayList Messages
		{
			get;
		}

		/// <summary>
		/// When implemented by a class, it generates the graph to a file given by the uri.
		/// </summary>
		/// <param name="graph">The owl graph the needs to be generated</param>
		/// <param name="uri">The uri representing the file that will be used as a destination of the graph</param>
		void GenerateOwl(IOwlGraph graph, string uri);

		/// <summary>
		/// When implemented by a class, it generates the graph to a file given by the uri.
		/// </summary>
		/// <param name="graph">The owl graph the needs to be generated</param>
		/// <param name="uri">The object of type Uri representing the file that will be used as a destination of the graph</param>
		void GenerateOwl(IOwlGraph graph, Uri uri);
	}
}